# Generated by Django 3.0.7 on 2021-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%y/%m/%s/')),
                ('facebook_link', models.URLField(max_length=255)),
                ('created_daten', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
